import cors from "cors";
import express from "express";
import { lms } from "./lib/lms.js";
import { authRoute } from "./route/auth.js";
import { studentRoute } from "./route/student.js";
import { teacherRoute } from "./route/teacher.js";
import { generalRoute } from "./route/general.js";
import { errorHandler } from "./lib/errorHandler.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use(generalRoute);
app.use("/auth", authRoute);
app.use("/student", studentRoute);
app.use("/teacher", teacherRoute);
app.use("/siswa", studentRoute);
app.use("/guru", teacherRoute);
app.use(errorHandler);
lms.init();
app.all("*", (req, res) => {res.status(404).json({ message: `Endpoint not found, ${req.originalUrl}.` });});

export { app };
